{{- $fullName := include "opanex-frontend-ng.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-route
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.opanexConfig.host }}`)
    services:
    - name: {{ $fullName }}
      port: {{ $svcPort }}
